### ISSUE TITLE
problem with slide

### ISSUE THREAD

**Issue by Hugonauta** [RupinS/CardDrawer#3]
when slide from left to right main navigationView is opened correctly but if in that moment, slide from the other side, the other navigationView is opened as a normal navigationDrawer, not as CardDrawer

**Comment by RupinSahu** [comment]
> when slide from left to right main navigationView is opened correctly but if in that moment, slide from the other side, the other navigationView is opened as a normal navigationDrawer, not as CardDrawer

Hey @Hugonauta , Sorry for too late reply. As per your use case, this CardDrawer wasn't designed to do so. Will check for this future enhancement if some other requests come.
